# Generated by Django 3.0.2 on 2020-01-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapp',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
